# Generated by Django 4.2.2 on 2023-09-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0005_remove_profile_is_verify_email_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Схемы вышивки', 'verbose_name_plural': 'Схемы вышивки'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
