# Generated by Django 4.2.2 on 2023-09-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0006_alter_product_options_remove_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
    ]
