# Generated by Django 4.2.2 on 2023-09-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0007_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vyazanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='products_images/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_project.productcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Схемы вязания',
                'verbose_name_plural': 'Схемы вязания',
            },
        ),
    ]
