# Generated by Django 4.2.2 on 2023-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0009_review_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='owner',
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
