# Generated by Django 4.2.2 on 2023-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0010_alter_review_options_remove_review_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=256, verbose_name='Имя')),
                ('recipient', models.CharField(max_length=256, verbose_name='Получатель')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('body', models.TextField(verbose_name='Текст письма')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
