# Generated by Django 4.2.2 on 2023-09-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0011_message_delete_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
